### ISSUE TITLE
Hello from a friend :)

### ISSUE THREAD

**Issue by tunggnu** [sf-writer-mdk/sf-writer-mdk#1]
Hi Marvin, long time no see.

Today I accidentally looked at the timeline on my GitHub page and saw activity by a user nicknamed `sf-writer-mdk`. I don't remember when I followed this nickname. But the word writer in the nickname got me thinking. I suddenly thought about you and your website _mywebdevelopmentodyssey.dev_. I used to read your posts from time to time until your website stopped working. Sometimes I wonder how your condition. It's good to know today you're still up and running on GitHub. I created this issue just to send you a greeting. Wishing you all good things.

You can safely delete this issue after reading it :)

**Comment by sf-writer-mdk** [comment]
Hi Tung. I remember our talks on the Discord app. I let the the site go, though I appreciate you taking a look at it. I've thought on and off again about whether or not to start a new blog, but I've got enough to worry about already as it is. I still struggle with depression. Currently I'm experiencing a lot of fatigue/tiredness with low back pain. Hopefully it will work itself out soon. 

I'm currently enrolled in Lambda School's live part time web development program. I was full time back in October but I had to take some time off and I restarted this March part time. 

As I recall, I believe you and your family had just had another child. I hope you and your family are all well. 

Do you prefer Tung or Tom?

Message me on Discord sometime. I look forward to hearing back from you.
